project:
  type: website

website:
  title: "<i class='bi bi-file-bar-graph'></i> ISSS608-VAA"
  navbar:
    left:
    - text: "<i class='bi bi-bar-chart-line'></i> Hands-On Exercise"
      menu:
        - text: "Hands-On Exercise 1: A Layered Grammar of Graphics: ggplot2 methods"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-On Exercise 2: Beyond ggplot2 Fundamentals"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-On Exercise 3-1: Programming Interactive Data Visualisation with R"
          href: "Hands-on_Ex/Hands-on_Ex03-1/Hands-on_Ex03-1.html"
        - text: "Hands-On Exercise 3-2: Programming Animated Statistical Graphics with R"
          href: "Hands-on_Ex/Hands-on_Ex03-2/Hands-on_Ex03-2.html"
    - text: "<i class='bi bi-graph-up'></i> Take-Home Exercise"
      menu:
        - text: "Take-Home Exercise 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
    right:
      - href: index.qmd
        text: "<i class='bi bi-house-door'></i> Home"
      - href: about.qmd
        text: "<i class='bi bi-person'></i> About"
  sidebar:
    - title: "Hands-On Exercise"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: "Hands-On Exercise"
          contents:
            - text: "1: A Layered Grammar of Graphics: ggplot2 methods"
              href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd
            - text: "2: Beyond ggplot2 Fundamentals"
              href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd
            - text: "3-1: Programming Interactive Data Visualisation with R"
              href: Hands-on_Ex/Hands-on_Ex03-1/Hands-on_Ex03-1.qmd
            - text: "3-2: Programming Animated Statistical Graphics with R"
              href: Hands-on_Ex/Hands-on_Ex03-2/Hands-on_Ex03-2.qmd
    - title: "Take-Home Exercise"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: "Take-Home Exercise"
          contents:
            - text: "1: Demographic Structures and Distribution of Singapore in 2024"
              href: Take-home_Ex/Take-home_Ex01/Take-home_Ex01.qmd
format:
  html:
    theme:
        light: flatly
        dark: darkly
    css: styles.css
    toc: true
    toc-depth: 4

editor: visual